[tool.ruff]
# Allow imports relative to the "src" and "test" directories.
src = ["backend", "tests"]

[tool.isort]
profile = "black"
line_length = 79
known_local_folder = ["api", "recipes", "foodgram_backend", "users", "tests"]
