DEFAULT_CHAR_FIELD_LENGTH = 200
USER_USERNAME_MAX_LENGTH = 150
USER_FIRST_NAME_MAX_LENGTH = 150
USER_LAST_NAME_MAX_LENGTH = 150
USER_EMAIL_MAX_LENGTH = 254
HEX_COLOR_LENGTH = 7
MIN_INGREDIENT_AMOUNT = 1
